- app/Http/Controllers/DocumentController.php
- app/Http/Controllers/UserController.php
- app/Http/Middleware/AuthUser.php
- app/Mail/OTPEmail.php
- database/migrations/2024_08_04_193503_document_types.php
- routes/api.php
Good evening, I just created a module for managing document types, Thank you
> add document type module

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/BarangayOfficialController.php
- app/Http/Controllers/DocumentController.php
- app/Http/Controllers/UserController.php
- composer.json
- composer.lock
- config/filesystems.php
- routes/api.php
I just added a success parameter for our api responses, thank you
> add sucess parameter

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/UserController.php
- composer.json
- composer.lock
- resources/views/document/template.blade.php
- routes/api.php
Good Day, This commit changes include:
- Include functionality for fetching users with pagination.
- Implemented pagination method. 
- Adjusted SQL query to support pagination.
- Adjusted route to ensure proper routing for the user view with pagination.
- Made changes to support the new pagination feature.
> Added pagination to view all users

- app/Http/Controllers/BarangayOfficialController.php
- app/Http/Controllers/UserController.php
Good Evening, This commit changes include:
- Updated `BarangayOfficialController.php` to implement pagination for viewing barangay officials.
- Added request parameters for page number and size.
- Modified SQL query to include LIMIT and OFFSET for pagination.
- Modified `UserController.php`:
- Implemented pagination in the `viewUsers()` method.
- Added optional fields for search and filtering.
- Adjusted SQL query to support pagination and optional search fields.
- Ensured that both controllers handle pagination and optional fields correctly, returning the appropriate data.
> Added pagination and optional fields to barangay and users view

- app/Http/Controllers/DocumentController.php
- routes/api.php
Good afternoon, I just created the api route for edit document type, kindly check, thank you
> add edit document type

- app/Http/Controllers/BarangayOfficialController.php
- app/Http/Controllers/DocumentController.php
Hi, Goodmorning, I just added a pagination for our document types and brgy. officials. Kindly check it, thank you
> add pagination for document types and officials

- app/Http/Controllers/BlotterController.php
- app/Http/Controllers/UserController.php
- database/migrations/2024_08_11_204522_create_blotter_reports_migration.php
Add Blotter Reports for Module and OTP for the user
> add blotter report and otp

- app/Http/Controllers/UserController.php
I just created a Email response to the user by their User ID
> email response for blotter

- app/Http/Controllers/UserController.php
Good Day, This commit include added validation to handle empty file uploads and provide appropriate feedback. Kindly review. Thank you!
> add validation for empty files

- app/Http/Controllers/UserController.php
Good Day, This commit includes:
- Added pagination to the users section for improved data navigation.
- Fixed 401 error issues.
- Updated user_id field to id for consistency.
- Added male_female field to capture gender information.
> added pagination to users

- app/Http/Controllers/UserController.php
- app/Mail/CreatedAppointmentMail.php
- resources/views/emails/created_appointment.blade.php
Good day, I have added functionality to send email notifications upon appointment creation. Kindly review, Thank you!
> add email for appointment creation

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/AppointmentController.php
- app/Http/Controllers/NewResidentController.php
- app/Http/Controllers/UserController.php
- database/migrations/2014_10_12_000000_create_users_table.php
- routes/api.php
Good Day, This commit changes include:
- implement new API methods for better handling of new resident data.
- Enhanced validation and error handling for smoother resident registration.
- Streamlined code for improved performance and maintainability.
> implement new resident API methods

- app/Http/Controllers/UserController.php
Good Day, This commit changes include:
- Implemented file upload processing in the noVerificationRegistration method.
- Enhanced the method to support multiple file uploads for new registrations.
> add file upload handling to noVerification registration

- app/Http/Controllers/NewResidentController.php
- app/Mail/DynamicMail.php
- resources/views/emails/dynamic_mail.blade.php
Good day, I have added functionality to send email notifications upon resident approval. This ensures residents are promptly informed when their approval status is updated.
> add email notification for resident approval

- app/Http/Controllers/BlotterController.php
- app/Http/Controllers/UserController.php
- database/migrations/2024_08_11_204522_create_blotter_reports_migration.php
- routes/api.php
Good day, This commit include voter status and current address fields to capture additional user details. Kindly review. Thank you!
> add voter status and current_address

- app/Http/Controllers/UserController.php
Good day, This commit changes include:
- Revise methods to enhance query efficiency and data consistency.
- Improved handling of null values in the database.
> enhance queries and improve data handling

- app/Http/Controllers/BlotterController.php
- app/Http/Controllers/UserController.php
- routes/api.php
Good day, This commit changes include:
- Added functionality in blotter to support pagination and filtering.
- Added response formatting for paginated data.
- Updated the routes to reflect changes in the Blotter and User controllers. 
> implement pagination and filtering in blotter

- app/Http/Controllers/BlotterController.php
- routes/api.php
Good day. These commit changes include updating the Blotter to implement edit functionality for Blotter reports, including file upload handling and route adjustments. Kindly review. Thank you!
> add edit for blotter

- app/Http/Controllers/NewResidentController.php
- composer.json
- composer.lock
- routes/api.php
Good day, I have added the PHP Spreadsheet package to enhance the handling of Excel and CSV files within the project. This integration will improve data processing and export capabilities. Thank you!
> added php spreadsheet package

- .gitignore
- app/Http/Controllers/AdminController.php
- app/Http/Controllers/BarangayOfficialController.php
- app/Http/Controllers/NewResidentController.php
- app/Http/Controllers/UserController.php
Good day, This commit includes:
- Fixed issue where the middle name was not being captured correctly.
- Removed composer.lock from the list to be included in .gitignore.
> fix no middle name

- app/Http/Controllers/UserController.php
Good day, This commit includes:
- Added supporting files object to better manage file uploads.
- Fixed issues related to file uploading for improved reliability.
> add supporting files obj

- app/Http/Controllers/NewResidentController.php
- routes/api.php
Good day, I have added the ability to approve residents directly within the edit endpoint. This enhancement streamlines the approval process by consolidating actions into a single endpoint.
> added resident approval functionality to edit endpoint

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/UserController.php
Good day! This commit includes:
- adding a view appointments feature to allow users to see the scheduled appointments. 
- implemented pagination in view appointment list function.
- fix email handling in OTP generation.
> add view appointments

- app/Http/Controllers/AppointmentController.php
- app/Http/Controllers/BlotterController.php
- resources/views/document/template.blade.php
- routes/api.php
Hi goodevening, I just created the flow for our appointment.
> create appointment flow

- app/Http/Controllers/NewResidentController.php
This commit include adding pagination to the view appointments feature for easier appointment management. Kindly review. Thank you!
> add pagination to view appointments

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/NewResidentController.php
- app/Http/Controllers/UserController.php
- app/Mail/DynamicMail.php
Good day, I have implemented a search feature to enhance data retrieval efficiency and made updates to the email functionality to improve communication processes.
> added search functionality and update email features

- app/Http/Controllers/NewResidentController.php
- app/Http/Controllers/UserController.php
- app/Mail/CreatedAppointmentMail.php
Good day, I have added the queuing number to the export functionality. This update ensures that queuing numbers are included in exported data for better tracking and organization.
> added queuing number to export functionality

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/AppointmentController.php
- app/Http/Controllers/DocumentController.php
- app/Http/Controllers/HistoryController.php
- app/Http/Controllers/UserController.php
- database/migrations/2024_07_25_062351_custom_tokens.php
- database/migrations/2024_07_31_185631_document_types.php
- database/migrations/2024_08_09_204555_create_appointments_table.php
- database/migrations/2024_08_17_121437_create_transaction_history_table.php
- routes/api.php
Good day, This commit changes include:
- Added download functionality for appointments.
- Updated the database schema in migration files, including new fields and indexes.
- Improve controllers for better code organization and performance.
- Enhanced validation and error handling in different methods.
- Corrected typos and removed outdated methods.
> add download feature for appointments

- app/Http/Controllers/BlotterController.php
Good day, I have fixed the search functionality within the BlotterReports module. This update ensures accurate and efficient search results when querying reports.
> fix search functionality in BlotterReports

- app/Http/Controllers/BlotterController.php
- app/Http/Controllers/HistoryController.php
- database/migrations/2024_08_11_204522_create_blotter_reports_migration.php
Goodevening, I just change complainant name instead of using id. Thank you
> change complainant id to complainant name

- app/Http/Controllers/BlotterController.php
- app/Http/Controllers/HistoryController.php
good afternoon, I add the missing field and fix the naming in the report for blotter and history
> add missing field and fix name in report

- app/Http/Controllers/BlotterController.php
- app/Http/Controllers/HistoryController.php
- routes/api.php
Already fix the status resolved condition and also add a downloading of users
> fix status condition and add downloading of users

- app/Http/Controllers/UserController.php
- database/migrations/2014_10_12_000000_create_users_table.php
- database/migrations/2024_08_10_081709_create_supporting_files_table.php
- database/seeders/DatabaseSeeder.php
This changes includes:
add missing fields to migrations
add separation to pending and non pending users
> remove random user seeder

- app/Helpers/helpers.php
- app/Http/Controllers/AdminController.php
- app/Http/Controllers/AppointmentController.php
- app/Http/Controllers/DocumentController.php
- app/Http/Controllers/NewResidentController.php
- app/Http/Controllers/UserController.php
- database/migrations/2024_09_01_131257_create_audit_logs_table.php
- routes/api.php
added for:
- editing users/deleting/adding individually
- appointments approving/denying/download+releasing
- document type adding/editing/deleting
- Requires bearer token to be add to noverificationregistration endpoint and downloadandrelease endpoint
> audit logs module

- app/Http/Controllers/AppointmentController.php
- app/Http/Controllers/UserController.php
- routes/api.php
Good morning. I remove end point from middleware route
> remove end point

- app/Http/Controllers/BlotterController.php
- app/Http/Controllers/UserController.php
- database/migrations/2024_08_11_204522_create_blotter_reports_migration.php
changing the approach for blotter report where instead of using ID for not residents now using a name
> changes to blotter

- app/Http/Controllers/BlotterController.php
- app/Http/Controllers/UserController.php
- database/migrations/2024_08_11_204522_create_blotter_reports_migration.php
I added officer on duty name and complaint name in blotter reports
> add officer on duty and complaint name

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/UserController.php
Good afternoon! I just fix some issues for audit and status in dashboard
- fix the issue caused by audit log not using correct id
- fix to status not showing correct values in dashboard
> fix issue of audit log and status

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/HistoryController.php
Good evening!, I made some fix to some issues of:
- Fix to dashboard
- Fix pending resident count in dashboard
- Fix sorting of audit logs
- Fixed id not showing in audit logs.
> fix some issues

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/BlotterController.php
Good evening! Fix another issue for blotter search
> fix blotter log

- app/Http/Controllers/AdminController.php
- routes/api.php
Good day, This update includes:
- Added HTTPS to API links for secure requests.
- Implemented dashboard filter functionality.
Thank you!
> add dashboard filter

- app/Http/Controllers/BlotterController.php
- app/Http/Controllers/HistoryController.php
- resources/views/document/blotter.blade.php
- routes/api.php
Good day,
This update includes:
> Added HTTPS to API links for download blotter.
> Implemented from and to generate report.
> Added functionality to download blotter reports per case and generate reports.
> create download in blotter per case and generate report

- app/Http/Controllers/BlotterController.php
Good day, I just fix issue in downloading blotter reports per case. Kindly review. Thank you!
> fix issue in download blotter per case

- app/Http/Controllers/AdminController.php
- app/Http/Controllers/HistoryController.php
> Added a filter for downloading blotter reports.
> Adjusted the view of the appointment list by adding "From" and "To" date filters.
> create filter for download blotter and adjust view appointment list

- app/Http/Controllers/BlotterController.php
- Revised functionality for downloading blotter reports per case.
- Added date and category filters to the blotter view for better filtering.
- Adjusted the appointment list view by adding "From" and "To" date filters.
> revise download blotter per case 

- app/Http/Controllers/BlotterController.php
> Added status filters for viewing blotters in the dashboard.
> add status filter in view blotters for dashboard

- app/Http/Controllers/AdminController.php
> Fixed an issue related to pending residents.
> fix for pending resident

- app/Http/Controllers/AdminController.php
> Fixed an issue related to filter in dashboard.
> fix filter in dashboard

- app/Http/Controllers/BlotterController.php
- Revised the downloadBlotterPDF to display the address correctly.
> revise downloadBlotterPDF displaying address

- app/Http/Controllers/HistoryController.php
- Revised category handling in the blotter form, allowing custom categories when 'Others' is selected.
> revise category for blotter

- app/Http/Controllers/UserController.php
- database/migrations/2024_10_07_115607_add_location_fields_to_users_table.php
- database/migrations/2024_10_08_170427_add_house_and_lot_details_to_users_table.php
good evening!, I add additional fields for residents to match with the Barangays resident Information
> add additional field for residents

- app/Http/Controllers/BlotterController.php
- Revised the viewAllBlotters function to properly handle category filtering.
> revise viewAllBlotters in category

- app/Http/Controllers/HistoryController.php
- Revised the templates for generating reports in both Blotter and Schedule for improved clarity and formatting.
> revise the template for generating reports in blotter and schedule

- app/Http/Controllers/AppointmentController.php
- Added dynamic handling of service information in the description template for document generation.
> add dynamic info handling for service in document generation

- app/Http/Controllers/DocumentController.php
Added update price, ensuring prices are properly reflected in the service documents.
> Added price to update

- app/Http/Controllers/NewResidentController.php
- app/Http/Controllers/UserController.php
remove unnecessary code for the current_address
> remove unnecessary code

- app/Http/Controllers/HistoryController.php
- Added remarks to the blotter download, including renaming complaint_remarks to Naration and adding the remarks field beside the status.
> add remarks in download blotter

- app/Http/Controllers/AppointmentController.php
Good Day, This commit changes include:
- Updated the `downloadAndReleaseDocument` function to dynamically generate document descriptions based on user details.
- Included logic to determine honorifics (Mr., Ms., Mrs.) based on gender and civil status.
- Included logic to determine gender pronoun (his/her) based on gender.
> add dynamic document generation with user details

- app/Http/Controllers/NewResidentController.php
- app/Http/Controllers/UserController.php
- app/Mail/CreatedAppointmentMail.php
- app/Mail/DynamicMail.php
- app/Mail/OTPEmail.php
- app/Mail/WelcomeEmail.php
- resources/views/emails/created_appointment.blade.php
- resources/views/emails/otp.blade.php
Good day, This update implements the following improvements:
- The email sender address has been changed.
- Email message templates have been modified.
> change email and update message templates

- app/Http/Controllers/NewResidentController.php
- app/Http/Controllers/UserController.php
- app/Mail/CreatedAppointmentMail.php
- app/Mail/OTPEmail.php
- resources/views/emails/created_appointment.blade.php
- resources/views/emails/dynamic_mail.blade.php
- resources/views/emails/otp.blade.php
Good day, This commit includes the following changes:
- Improved the formatting of received emails to ensure a clearer, more professional appearance and better readability for users.
> enhance received email format

- resources/views/document/blotter.blade.php
- resources/views/document/template.blade.php
Good day, This commit improves the layout of the document format for better presentation and clarity. Kindly review. Thank you!
> enhance document format layout

- app/Http/Controllers/UserController.php
- package-lock.json
change the logic for count_schedules slot limit when scheduling
> change the logic for count_schedules
